version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ai-doc-backend
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=/app/data/documents.db
      - API_HOST=0.0.0.0
      - API_PORT=8001
    env_file:
      - ./backend/.env
    volumes:
      - backend_data:/app/data
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('https://docsummarizer.onrender.com/')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - ai-doc-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ai-doc-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - ai-doc-network

volumes:
  backend_data:
    driver: local

networks:
  ai-doc-network:
    driver: bridge